#!/usr/bin/env node
/**
 * One-shot: pull the agentic (x-alpha) paths + schemas out of openapi.yaml
 * into openapi.agentic.yaml. Run once when the split is set up (or after
 * a platform openapi sync brings in new agentic content that needs to be
 * captured in the overlay). Idempotent — re-running just refreshes the
 * overlay to match whatever the base currently defines.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as yaml from 'js-yaml';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const BASE = resolve(ROOT, 'openapi.yaml');
const OVERLAY = resolve(ROOT, 'openapi.agentic.yaml');

// Schema names that belong to the agentic surface. Kept as an explicit
// allowlist because YAML has no marker on schemas equivalent to `x-alpha`
// on paths — and because a couple names (Mandate, MandateRule) do not
// share a common prefix.
//
// It lists only schemas the alpha paths OWN. Shared ones they also reference
// (Address, KSUID, Meta, NetworkId, ProblemDetails, RecipientRequest,
// ValidationError) are reachable from non-alpha paths too, so a sync that
// stripped the alpha surface would still leave them in the base — copying
// them here would only create a second definition to keep in step.
//
// `tests/client/spec-guards.test.ts` fails if an alpha path starts
// referencing an agentic-only schema this list does not carry.
const AGENTIC_SCHEMAS = new Set([
  'PaymentAgentResponse',
  'PaymentAgentSignerGroupRef',
  'AgenticAction',
  'AgenticBlocker',
  'AgenticClientPolicy',
  'AgenticProposalsProgress',
  'AgenticActionDownstream',
  'AgenticAttachment',
  'AgenticChatMessage',
  'AgenticDocumentAttachment',
  'AgenticInstruction',
  'AgenticInstructionsResult',
  'AgenticProposal',
  'AgenticProposalsResult',
  'AmendMandateRequest',
  'ApproveMandateRequest',
  'CancelMandateRequest',
  'CreatePaymentAgentRequest',
  'CreateBankDestinationAction',
  'CreateCryptoDestinationAction',
  'CreateInstructionsRequest',
  'CreateMandateAction',
  'CreateMandateRequest',
  'CreateProposalsRequest',
  'CreateScheduledPaymentsAction',
  'CreateAutoAccountAction',
  'CreateScheduledPaymentRequest',
  'DeveloperFee',
  'MandateBudget',
  'MandateBudgetLine',
  'MandateVersion',
  'RegisteredAgenticClientPolicy',
  'ScheduledPaymentList',
  'Mandate',
  'MandateResponse',
  'MandateRule',
  'ScheduledPaymentResponse',
  'InsightEvidence',
  'InsightItem',
  'InsightSnapshotBalance',
  'InsightSnapshotUpcoming',
  'InsightSnapshot',
  'InsightReport',
]);

const base = yaml.load(readFileSync(BASE, 'utf8'));

// Pull paths marked `x-alpha: true`.
const agenticPaths = {};
for (const [route, def] of Object.entries(base.paths ?? {})) {
  if (def && def['x-alpha'] === true) {
    agenticPaths[route] = def;
  }
}

// Pull the listed schemas.
const agenticSchemas = {};
const allSchemas = base.components?.schemas ?? {};
for (const name of AGENTIC_SCHEMAS) {
  if (name in allSchemas) {
    agenticSchemas[name] = allSchemas[name];
  } else {
    console.warn(`warning: overlay allowlist references missing schema ${name}`);
  }
}

const overlay = {
  paths: agenticPaths,
  components: { schemas: agenticSchemas },
};

writeFileSync(
  OVERLAY,
  '# SDK-owned overlay: alpha-tagged (x-alpha) agentic surface.\n' +
    '# Regenerated by scripts/extract-agentic.mjs.\n' +
    '# Merged into openapi.yaml by scripts/merge-openapi.mjs on `npm run generate`.\n' +
    yaml.dump(overlay, { lineWidth: 1000, noRefs: true })
);
console.log(
  `wrote ${OVERLAY} — ${Object.keys(agenticPaths).length} paths, ${Object.keys(agenticSchemas).length} schemas`
);
